openapi: 3.0.0
info:
  title: CareConnect Backend API
  description: Backend service for the Timesheet frontend.
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /timeSheet:
    get:
      summary: Get timesheet
      responses:
        '200':
          description: A timesheet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorklogItem'
        '400':
          description: Missing or invalid parameters
        '401':
          description: Authentication failed
        '500':
          description: Internal server error
components:
  schemas:
    WorklogItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: "2024-04-01"
        project:
          type: string
          example: "Project A"
        worklog:
          type: string
          example: "Worklog for Project A"
        duration:
          type: string
          example: "3 hours"